---
packages:
  - packages/*
catalog:
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/fad': ^1.2.1
  '@iconify-json/svg-spinners': ^1.2.2
  '@iconify-json/vscode-icons': ^1.2.16
  '@lincy/async-validation': ^1.3.0
  '@lincy/eslint-config': ^5.5.0
  '@lincy/stylelint-config': ^2.0.1
  '@lincy/unocss-base-config': ^2.2.1
  '@lincy/utils': ^0.6.2
  '@tanstack/vue-query': ^5.67.2
  '@types/locutus': ^0.0.8
  '@types/mockjs': ^1.0.10
  '@types/node': ^22.13.10
  '@types/polyfill-library': ^3.108.4
  '@types/qs': ^6.9.18
  '@unhead/vue': ^1.11.20
  '@unocss/eslint-plugin': ^65.5.0
  '@unocss/reset': ^65.5.0
  '@vitejs/plugin-vue': ^5.2.1
  '@vitejs/plugin-vue-jsx': ^4.1.1
  '@vue-macros/volar': ^0.30.15
  '@vueuse/core': ^13.0.0
  '@vueuse/router': ^13.0.0
  axios: ^1.8.2
  cross-env: ^7.0.3
  default-passive-events: ^2.0.0
  element-plus: ^2.9.6
  eslint: ^9.22.0
  eslint-plugin-format: ^1.0.1
  js-cookie: ^3.0.5
  lint-staged: ^15.4.3
  locutus: ^2.0.32
  lodash: ^4.17.21
  mitt: ^3.0.1
  mockjs: ^1.1.0
  pinia: ^3.0.1
  polyfill-library: ^4.8.0
  qs: ^6.14.0
  sass: ^1.85.1
  simple-git-hooks: ^2.11.1
  store2: ^2.14.4
  typescript: ^5.8.2
  unocss: ^65.5.0
  unplugin-auto-import: ^19.1.1
  unplugin-icons: ^22.1.0
  unplugin-vue-components: ^28.4.1
  unplugin-vue-macros: ^2.14.5
  url-search-params-polyfill: ^8.2.5
  vite: ^6.2.1
  vite-plugin-inspect: ^11.0.0
  vite-plugin-mock: ^3.0.2
  vite-plugin-progress: ^0.0.7
  vue: ^3.5.13
  vue-countup-v3: ^1.4.2
  vue-router: ^4.5.0
  vue-tsc: ^2.2.8
  vue3-seamless-scroll: ^3.0.2
peerDependencyRules:
  ignoreMissing:
    - rollup
    - postcss
    - terser
    - prettier
    - esbuild
