/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    GlobalDigital: typeof import('./components/global/digital.tsx')['default']
    GlobalFooter: typeof import('./components/global/footer.vue')['default']
    GlobalHeader: typeof import('./components/global/header.vue')['default']
    HomeCategory: typeof import('./components/home/category.vue')['default']
    HomeRecommend: typeof import('./components/home/recommend.vue')['default']
    NewsArticleRec: typeof import('./components/news/article-rec.vue')['default']
    NewsRecommend: typeof import('./components/news/recommend.vue')['default']
    OtherRelatedRecom: typeof import('./components/other/related-recom.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
